Upgraded to Typescript@3.6, Vega@5.2, Vega-Lite@3.4, Webpack@4.1
vega/voyager pull request #886
Opened 2022-04-06 19:43 UTC by siyaoL1

List of upgraded dependencies:

- vega
- vega-lite
- compassql
- vega-datasets
- vega-expression
- vega-tooltip
- vega-typings
- vega-util
- vega-functions
- css-loader
- extract-text-webpack-plugin
- file-loader
- html-webpack-plugin
- postcss-loader
- react-dnd
- react-dev-utils
- react-hot-loader
- sass-loader
- source-map-loader
- terser-webpack-plugin
- ts-jest
- ts-loader
- typescript
- url-loader
- webpack
- webpack-cli
- webpack-dev-server
- webpack-manifest-plugin
- @types/webpack
- @types/node
- @types/react

2022-04-06 20:01 UTC, domoritz commented on package.json
> +    "redux-thunk": "2.2.0",
What's the problem with `^2.2.0`?

2022-04-06 20:02 UTC, domoritz commented on package.json
> +    "vega-typings": "0.7.2",
Are those included in vega now? If yes, remove it here.

2022-04-06 20:02 UTC, domoritz commented on package.json
> +    "@types/node": "~8.10.64"
Can we move to a supported node version?

2022-04-06 20:02 UTC, domoritz requested changes
See comments

2022-04-07 21:11 UTC, siyaoL1 commented
I will work on addressing the comments

2022-04-29 19:16 UTC, domoritz commented
Please fix the tests

2022-04-29 19:16 UTC, closed without merging

2022-05-27 01:38 UTC, domoritz commented
Let me know when tests pass.

2022-05-31 18:08 UTC, domoritz approved these changes
Please remove [yarn-error.log](https://github.com/vega/voyager/pull/886/files#diff-a2b6efbfdcf1ef38207392bbe0d2316d07f49cb87184999c894e9535e2eb65cc). 

Did you check that the app works as expected? If so, I will make a final pass and merge after you address my comments.

2022-05-31 18:08 UTC, domoritz commented on config/webpack.config.lib.js
> +// const getClientEnvironment = require('./env');
please remove commented out code

2022-05-31 18:08 UTC, domoritz commented on config/webpack.config.lib.js
> +// const env = getClientEnvironment(publicUrl);
same as above

2022-06-05 16:23 UTC, domoritz commented
@siyaoL1 is working on support CSV and then we can merge this.